- name: "Clone mermeid"
  git:
    version: "{{ mermeid_version }}"
    repo: "{{ mermeid_git_repo }}"
    dest: "{{ mermeid_source }}"
  become: true

- name: "add permissions for {{ mermeid_source }}"
  file:
    path: "{{ mermeid_source }}"
    recurse: yes
    owner: "{{ exist_user }}"
    group: "{{ exist_user }}"
  become: true

- name: "add template for {{ items }}"
  template:
    src: "{{ item }}"
    dest: "{{ mermeid_local_config }}/{{ item | regex_replace('\\.j2','')}}_{{ instance_name }}"
  with_items:
  - "mermeid_configuration.xml.j2"
  - "login.xqm.j2"  
  become_user: "{{ worker_name }}"
  become: true

- name: "Copy bibliograhpy, redirect"
  copy:
    remote_src: yes
    src: "{{ mermeid_local_config }}/{{ item }}"
    dest: "{{ mermeid_local_config }}/{{ item | regex_replace('_distro','')}}_{{ instance_name }}"
  with_items:
  - "redirect_host.xqm_distro"
  - "standard_bibliography.xml_distro"
  become_user: "{{ worker_name }}"
  become: true

- name: "create orbeon dir"
  file:
    path: "{{ orbeon_mei_form_path }}"
    state: "directory"
    owner: "tomcat"
    group: "tomcat"
  become: true

- name: "place mei-form in orbeon"
  copy:
    remote_src: yes
    src: "{{ mermeid_source }}/trunk/orbeon/mei_form.jsp"
    dest: "{{ orbeon_mei_form_path }}/index.jsp"
    owner: "tomcat"
    group: "tomcat"
  become: true

- name: "copy orbeon properties to webapps"
  copy:
    remote_src: yes
    src: "{{ mermeid_source }}/trunk/orbeon/properties-local.xml"
    dest: "/var/lib/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml"
    owner: "tomcat"
    group: "tomcat"
  become: true

- name: "build MerMEId"
  shell: "ant clean && ant -Dwebapp.instance={{ instance_name }}"
  args:
    chdir: "{{ mermeid_source }}/trunk"
  become_user: "{{ worker_name }}"
  become: true

- name: "deploy MerMeID"
  copy:
    remote_src: yes
    src: "{{ mermeid_source }}/trunk/mermeid/editor.war"
    dest: "/var/lib/tomcat/webapps/editor.war"
    owner: "tomcat"
    group: "tomcat"
  become: true

- name: "install MerMEId database to exist-db"
  shell: "ant upload -Dwebapp.instance=mymermeid -Dhostport=localhost:8080 -Dserver.pass={{ existdb_password[inventory_hostname] }}"
  args:
    chdir: "{{ mermeid_source }}/trunk"

- name: "run xqueries to prepare exist-db (xchmod, create public dir)"
  shell: "bin/client.sh -u admin -P \"{{ existdb_password[inventory_hostname] }}\" -F {{ mermeid_source }}/trunk/xqueries/{{ item }} -ouri=xmldb:exist://localhost:{{ exist_http_port }}/exist/xmlrpc && touch {{ exist_home }}/exist/webapp/WEB-INF/data/.{{ item }}"
  args:
    chdir: "{{ exist_home }}/exist"
    creates: "{ exist_home }}/exist/webapp/WEB-INF/data/.{{ item }}"
  with_items:
  - "bootstrap_xchmod.xq"
  - "xchmod.xq"
  - "create_public.xq"
  become_user: "{{ worker_name }}"
  become: true
  environment:
    EXIST_HOME: "{{ exist_home }}/exist"

#- name: "create public folder"
#- name: "run xchmod.xq"

    #- name: "grant write permissions from API"
    #get_url:
    # url: "{{ item }}"
    #   force_basic_auth: "yes"
    # url_username: "admin"
    #    url_password: "existdb_password[inventory_hostname]"
    # dest: "/home/centos/result"
    # with_items:
    #- "http://localhost:8080/exist/rest/db/mermeid/bootstrap_xchmod.xq"
    #- "http://localhost:8080/exist/rest/db/apps/filter/xchmod.xq"
    #- "http://localhost:8080/exist/rest/db/mermeid/xchmod.xq"

- name: "Write htpasswd file"
  htpasswd:
    path: "{{ mermeid_basic_auth_file }}" 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "root"
    group: "apache"
    mode: "0640"
  with_items: "{{ mermeid_users }}"
  become: true
